services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app

  server:
    build: ./server
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules

    working_dir: /app
    env_file:
      - ./server/.env
